version: '3.9'
services:
  db:
    container_name: omni-postgres-docker
    image: postgres
    restart: always
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - ./data:/data/db
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  api:
    container_name: omni-nodejs-docker
    restart: always
    build: .
    ports:
      - 5000:${NODE_PORT}
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      NODE_PORT: ${NODE_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: omni-postgres-docker
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app


volumes: 
  data: {}